[build]
builder = "NIXPACKS"


[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port 8080"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5


[variables]
PYTHONUNBUFFERED = "1"
