name: Ping Telegram

on:
  push:
    branches: ["**"]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send simple message
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          set -e
          curl -sS -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            --data-urlencode "text=✅ GitHub Actions жив. Коммит: $GITHUB_SHA (ветка: $GITHUB_REF_NAME)" 
